# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  kiwiNet:

services:
  couchdb0:
    container_name: couchDBOrg1Peer0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=kiwi
      - COUCHDB_PASSWORD=abc123
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for kiwi map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - kiwiNet

  peer0.org1.kiwi.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchDBOrg1Peer0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=kiwi
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=abc123
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchDBPeer1Org1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=kiwi
      - COUCHDB_PASSWORD=abc123
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for kiwi map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - kiwiNet

  peer1.org1.kiwi.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchDBPeer1Org1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=kiwi
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=abc123
    depends_on:
      - couchdb1

  couchdb2:
    container_name: couchDBPeer0Org2
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=kiwi
      - COUCHDB_PASSWORD=abc123
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"
    networks:
      - kiwiNet

  peer0.org2.kiwi.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchDBPeer0Org2:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=kiwi
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=abc123
    depends_on:
      - couchdb2

  couchdb3:
    container_name: couchDBPeer1Org2
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=kiwi
      - COUCHDB_PASSWORD=abc123
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for kiwi map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      - kiwiNet

  peer1.org2.kiwi.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchDBPeer1Org2:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=kiwi
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=abc123
    depends_on:
      - couchdb3
